### ISSUE TITLE
Robolectric 3.0

### ISSUE THREAD

**Issue by younes0** [hitherejoe/Android-Boilerplate#1]
Very neat example thanks.
I suggest to update the repo with Robolectric 3.0 which supports recent Android API version.
See instructions here: https://www.bignerdranch.com/blog/triumph-android-studio-1-2-sneaks-in-full-testing-support/

**Comment by hitherejoe** [comment]
No problem! And good call, i'll update that today :+1:

**Comment by hitherejoe** [comment]
Updated!
