### ISSUE TITLE
Project could benefit from some more DI examples around UI

### ISSUE THREAD

**Issue by ZacSweers** [hitherejoe/Android-Boilerplate#7]
Should probably have some more fleshed out dependency injection examples if you want it to be a resource on good DI practices

**Comment by hitherejoe** [comment]
@hzsweers The inject annotation is used within the [DataManager](https://github.com/hitherejoe/Android-Boilerplate/blob/master/app/src/main/java/com/hitherejoe/androidboilerplate/data/DataManager.java) class for the dependancies within it, not sure if you saw the use there? But it's not used much elsewhere, I can always expand on the use of injection if you feel it needs to be

**Comment by ZacSweers** [comment]
Ah must have missed that. I did a search on the repository itself for
"@Inject" but it turned up zero results, should've gone and done a manual
check as well. I think it would benefit from more examples, particularly in
areas dealing with UI.

**Comment by hitherejoe** [comment]
@hzsweers github search has let me down many a times, no worries! I agree with that though in regards to UI cases, i'll add some uses in soon when I get a chance :+1:

**Comment by ZacSweers** [comment]
Sounds good!

**Comment by ZacSweers** [comment]
Oh my god Joe I didn't know we've been friends this long 👀
